### ISSUE TITLE
hello，if you show this global modal in react navigation modal stack Screen，this global modal cannot show on ios

### ISSUE THREAD

**Issue by mouxuefei** [roycechua/rn-global-modal-control-example#1]

**Comment by roycechua** [comment]
> _No description provided._

Hello mouxufei, I haven't tried this with a React Navigation Modal yet but on iOS, you really cannot open two modals using the built-in RN modal at the same time because of a bug in React Native or its implementation of the Modal as mentioned [here](https://github.com/react-native-modal/react-native-modal/issues/30#issuecomment-342111859). I have experienced a scenario where there is an options modal (functioning like a bottom sheet) and it opens a new modal. On Android, this is not an issue but on iOS it is so what I ended up doing is to add a delay using setTimeout() not the most ideal but it works. This is also the recommendation of the author of the react-native-modal library [https://github.com/react-native-modal/react-native-modal/issues/30#issuecomment-304179412](https://github.com/react-native-modal/react-native-modal/issues/30#issuecomment-304179412) which is also based on the built-in React Native modal.

**Comment by roycechua** [comment]
I will close this issue now because this issue is not related to the example but rather the implementation of the built-in React Native modal. I recommend to just use the React Navigation Screen instead of Modal if you want to launch another modal from inside of it.
